steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:$BUILD_ID
      - --build-arg
      - VITE_GOOGLE_MAPS_API_KEY=${_MAPS_API_KEY}
      - --build-arg
      - VITE_API_BASE_URL=${_API_BASE_URL}
      - --build-arg
      - VITE_EVENT_SOURCE=${_EVENT_SOURCE}
      - --build-arg
      - VITE_AGENT_SOURCE=${_AGENT_SOURCE}
      - .
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:$BUILD_ID
substitutions:
  _REGION: asia-east1
  _REPOSITORY: sidequest
  _MAPS_API_KEY: ""
  _API_BASE_URL: /api/v1
  _EVENT_SOURCE: api
  _AGENT_SOURCE: agent
options:
  logging: CLOUD_LOGGING_ONLY
