"""High-Fidelity Mock Seed Dataset for Taipei Weekend Events and Venues (PRD Compliant)."""

from datetime import datetime, timezone
from typing import List
from app.models.event import Event, EventCategory, Location, RegistrationStatus
from app.models.crowd import CrowdLevel, TrendDirection, VenueLiveStatus


class MockDataSeeder:
    """Provides rich, realistic Taipei city datasets for local testing, demos, and Firestore seeding."""

    @classmethod
    def get_seed_venues(cls) -> List[VenueLiveStatus]:
        now_iso = datetime.now(timezone.utc).isoformat()
        return [
            VenueLiveStatus(
                venue_id="venue_huashan",
                venue_name="華山1914文化創意產業園區",
                district="中正區",
                location=Location(
                    latitude=25.0441,
                    longitude=121.5294,
                    address="台北市中正區八德路一段1號",
                    district="中正區",
                    mrt_station="忠孝新生站 (BL14 / O07)",
                    mrt_distance_meters=250,
                ),
                crowd_score=92,
                crowd_level=CrowdLevel.OVERLOADED,
                wait_time_minutes=35,
                trend=TrendDirection.RISING,
                capacity_percentage=95,
                temperature_c=34.5,
                uv_index=8.5,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_songshan",
                venue_name="松山文創園區",
                district="信義區",
                location=Location(
                    latitude=25.0438,
                    longitude=121.5607,
                    address="台北市信義區光復南路133號",
                    district="信義區",
                    mrt_station="國父紀念館站 (BL17) / 市政府站 (BL18)",
                    mrt_distance_meters=450,
                ),
                crowd_score=85,
                crowd_level=CrowdLevel.HIGH,
                wait_time_minutes=25,
                trend=TrendDirection.STABLE,
                capacity_percentage=88,
                temperature_c=34.0,
                uv_index=8.2,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_popop",
                venue_name="POPOP Taipei 瓶蓋工廠台北製造所",
                district="南港區",
                location=Location(
                    latitude=25.0531,
                    longitude=121.6062,
                    address="台北市南港區南港路二段13號",
                    district="南港區",
                    mrt_station="南港站 (BL22 / 捷運地下街直通)",
                    mrt_distance_meters=180,
                ),
                crowd_score=28,
                crowd_level=CrowdLevel.LOW,
                wait_time_minutes=0,
                trend=TrendDirection.STABLE,
                capacity_percentage=30,
                temperature_c=32.0,
                uv_index=7.5,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_clab",
                venue_name="C-LAB 臺灣當代文化實驗場",
                district="大安區",
                location=Location(
                    latitude=25.0396,
                    longitude=121.5388,
                    address="台北市大安區建國南路一段177號",
                    district="大安區",
                    mrt_station="忠孝復興站 (BL15) / 忠孝新生站 (BL14)",
                    mrt_distance_meters=550,
                ),
                crowd_score=22,
                crowd_level=CrowdLevel.LOW,
                wait_time_minutes=0,
                trend=TrendDirection.STABLE,
                capacity_percentage=25,
                temperature_c=32.5,
                uv_index=7.8,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_tfam",
                venue_name="臺北市立美術館 (TFAM)",
                district="中山區",
                location=Location(
                    latitude=25.0722,
                    longitude=121.5248,
                    address="台北市中山區中山北路三段181號",
                    district="中山區",
                    mrt_station="圓山站 (R14)",
                    mrt_distance_meters=600,
                ),
                crowd_score=45,
                crowd_level=CrowdLevel.MODERATE,
                wait_time_minutes=5,
                trend=TrendDirection.STABLE,
                capacity_percentage=48,
                temperature_c=31.8,
                uv_index=7.2,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_kishuan",
                venue_name="紀州庵文學森林",
                district="中正區",
                location=Location(
                    latitude=25.0217,
                    longitude=121.5222,
                    address="台北市中正區同安街107號",
                    district="中正區",
                    mrt_station="古亭站 (G09 / O05)",
                    mrt_distance_meters=650,
                ),
                crowd_score=18,
                crowd_level=CrowdLevel.LOW,
                wait_time_minutes=0,
                trend=TrendDirection.STABLE,
                capacity_percentage=20,
                temperature_c=30.5,
                uv_index=6.0,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_chifeng",
                venue_name="赤峰街老屋文創聚落",
                district="大同區",
                location=Location(
                    latitude=25.0545,
                    longitude=121.5204,
                    address="台北市大同區赤峰街49巷",
                    district="大同區",
                    mrt_station="中山站 (R11 / G14 捷運地下街R7出口)",
                    mrt_distance_meters=120,
                ),
                crowd_score=68,
                crowd_level=CrowdLevel.MODERATE,
                wait_time_minutes=15,
                trend=TrendDirection.RISING,
                capacity_percentage=72,
                temperature_c=33.8,
                uv_index=8.0,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_tpac",
                venue_name="臺北表演藝術中心 (TPAC)",
                district="士林區",
                location=Location(
                    latitude=25.0877,
                    longitude=121.5262,
                    address="台北市士林區劍潭路1號",
                    district="士林區",
                    mrt_station="劍潭站 (R15 捷運站直通)",
                    mrt_distance_meters=80,
                ),
                crowd_score=36,
                crowd_level=CrowdLevel.MODERATE,
                wait_time_minutes=0,
                trend=TrendDirection.STABLE,
                capacity_percentage=40,
                temperature_c=32.2,
                uv_index=7.6,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_tmc",
                venue_name="臺北流行音樂中心 (TMC)",
                district="南港區",
                location=Location(
                    latitude=25.0519,
                    longitude=121.5975,
                    address="台北市南港區市民大道八段99號",
                    district="南港區",
                    mrt_station="昆陽站 (BL21) / 南港站 (BL22)",
                    mrt_distance_meters=400,
                ),
                crowd_score=30,
                crowd_level=CrowdLevel.LOW,
                wait_time_minutes=0,
                trend=TrendDirection.STABLE,
                capacity_percentage=35,
                temperature_c=32.1,
                uv_index=7.4,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_daan",
                venue_name="大安森林公園生態水池區",
                district="大安區",
                location=Location(
                    latitude=25.0297,
                    longitude=121.5358,
                    address="台北市大安區新生南路二段1號",
                    district="大安區",
                    mrt_station="大安森林公園站 (R06)",
                    mrt_distance_meters=50,
                ),
                crowd_score=62,
                crowd_level=CrowdLevel.MODERATE,
                wait_time_minutes=0,
                trend=TrendDirection.FALLING,
                capacity_percentage=60,
                temperature_c=35.0,
                uv_index=9.2,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_dadaocheng",
                venue_name="大稻埕碼頭貨櫃市集",
                district="大同區",
                location=Location(
                    latitude=25.0569,
                    longitude=121.5076,
                    address="台北市大同區民生西路底大稻埕碼頭五號水門",
                    district="大同區",
                    mrt_station="北門站 (G13) / 雙連站 (R12)",
                    mrt_distance_meters=1100,
                ),
                crowd_score=89,
                crowd_level=CrowdLevel.OVERLOADED,
                wait_time_minutes=30,
                trend=TrendDirection.RISING,
                capacity_percentage=92,
                temperature_c=35.8,
                uv_index=9.5,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_rongjin",
                venue_name="榕錦時光生活園區",
                district="大安區",
                location=Location(
                    latitude=25.0289,
                    longitude=121.5268,
                    address="台北市大安區金華街167號",
                    district="大安區",
                    mrt_station="東門站 (R07 / O06)",
                    mrt_distance_meters=480,
                ),
                crowd_score=76,
                crowd_level=CrowdLevel.HIGH,
                wait_time_minutes=20,
                trend=TrendDirection.STABLE,
                capacity_percentage=80,
                temperature_c=33.5,
                uv_index=8.1,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_bopiliao",
                venue_name="剝皮寮歷史街區",
                district="萬華區",
                location=Location(
                    latitude=25.0371,
                    longitude=121.5020,
                    address="台北市萬華區廣州街101號",
                    district="萬華區",
                    mrt_station="龍山寺站 (BL10)",
                    mrt_distance_meters=300,
                ),
                crowd_score=40,
                crowd_level=CrowdLevel.MODERATE,
                wait_time_minutes=0,
                trend=TrendDirection.STABLE,
                capacity_percentage=42,
                temperature_c=32.8,
                uv_index=7.0,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_treasurehill",
                venue_name="寶藏巖國際藝術村",
                district="中正區",
                location=Location(
                    latitude=25.0116,
                    longitude=121.5332,
                    address="台北市中正區汀州路三段230巷14弄2號",
                    district="中正區",
                    mrt_station="公館站 (G07)",
                    mrt_distance_meters=850,
                ),
                crowd_score=52,
                crowd_level=CrowdLevel.MODERATE,
                wait_time_minutes=0,
                trend=TrendDirection.STABLE,
                capacity_percentage=55,
                temperature_c=33.0,
                uv_index=8.4,
                last_updated=now_iso,
            ),
            VenueLiveStatus(
                venue_id="venue_ntsec",
                venue_name="國立臺灣科學教育館",
                district="士林區",
                location=Location(
                    latitude=25.0957,
                    longitude=121.5165,
                    address="台北市士林區士商路189號",
                    district="士林區",
                    mrt_station="士林站 (R16 接駁公車 / 步行)",
                    mrt_distance_meters=900,
                ),
                crowd_score=58,
                crowd_level=CrowdLevel.MODERATE,
                wait_time_minutes=10,
                trend=TrendDirection.STABLE,
                capacity_percentage=60,
                temperature_c=25.0,
                uv_index=0.0,
                last_updated=now_iso,
            ),
        ]

    @classmethod
    def get_seed_events(cls) -> List[Event]:
        now_iso = datetime.now(timezone.utc).isoformat()
        return [
            # 1. Major City Event (Exhibition / Culture)
            Event(
                id="evt_wenbo_2026",
                title="2026 臺灣文博會：文化百景與創意島嶼大展",
                category=EventCategory.EXHIBITION,
                description="全台最大文化創意博覽會，匯聚台灣原創IP、文創品牌與沉浸式多媒體展區。週末主展館人流極高，需排隊入場。",
                venue_name="華山1914文化創意產業園區 東2館/中4館",
                venue_id="venue_huashan",
                location=Location(
                    latitude=25.0441,
                    longitude=121.5294,
                    address="台北市中正區八德路一段1號",
                    district="中正區",
                    mrt_station="忠孝新生站 (BL14 / O07)",
                    mrt_distance_meters=250,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-15T10:00:00Z",
                end_time="2026-08-25T18:00:00Z",
                tags=["文博會", "展覽", "文創", "IP", "熱門", "室內", "情侶"],
                price_type="free",
                price_amount=0,
                registration_status=RegistrationStatus.FREE_ENTRY,
                source_platform="臺灣文博會官方",
                capacity=800,
                estimated_duration_hours=2.5,
                rating=4.7,
                review_count=520,
                image_url="https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=60",
                source_url="https://creativexpo.tw",
                last_updated=now_iso,
            ),
            # 2. Market Event (Songshan)
            Event(
                id="evt_songshan_craft_fair",
                title="2026 臺北夏日文創生活節＆風格選物市集",
                category=EventCategory.MARKET,
                description="匯集超過120家台灣原創手作品牌與獨立咖啡甜點，現場排隊動線長且人潮高度密集。",
                venue_name="松山文創園區 2-4號倉庫",
                venue_id="venue_songshan",
                location=Location(
                    latitude=25.0438,
                    longitude=121.5607,
                    address="台北市信義區光復南路133號",
                    district="信義區",
                    mrt_station="國父紀念館站 (BL17)",
                    mrt_distance_meters=450,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-16T11:00:00Z",
                end_time="2026-08-24T19:00:00Z",
                tags=["文創", "市集", "手作", "咖啡", "冷氣", "熱門"],
                price_type="free",
                price_amount=0,
                registration_status=RegistrationStatus.FREE_ENTRY,
                source_platform="Accupass",
                capacity=800,
                estimated_duration_hours=2.0,
                rating=4.4,
                review_count=480,
                image_url="https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop&q=60",
                source_url="https://www.accupass.com/event/songshan_craft_2026",
                last_updated=now_iso,
            ),
            # 3. Dispersal Gem 1 (Popop Taipei Craft & Cafe)
            Event(
                id="evt_popop_craft_workshop",
                title="【舒適私房首選】瓶蓋工廠創客自造木作與職人手沖咖啡展",
                category=EventCategory.CRAFT,
                description="寬敞開闊的工業風歷史廠房，人流適中舒適、冷氣充足。捷運南港站地下街直達，免於烈日曝曬，提供木作DIY、皮革體驗與冠軍咖啡品嚐。",
                venue_name="POPOP Taipei 瓶蓋工廠台北製造所",
                venue_id="venue_popop",
                location=Location(
                    latitude=25.0531,
                    longitude=121.6062,
                    address="台北市南港區南港路二段13號",
                    district="南港區",
                    mrt_station="南港站 (BL22 地下街直通)",
                    mrt_distance_meters=180,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-17T10:30:00Z",
                end_time="2026-08-24T18:30:00Z",
                tags=["手作", "木工", "咖啡", "冷氣", "地下街直通", "免排隊", "文創私房推薦"],
                price_type="free",
                price_amount=0,
                registration_status=RegistrationStatus.OPEN,
                source_platform="Accupass",
                capacity=400,
                estimated_duration_hours=2.0,
                rating=4.8,
                review_count=195,
                image_url="https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=60",
                source_url="https://www.accupass.com/event/popop_craft_2026",
                last_updated=now_iso,
            ),
            # 4. Tech / Community Event 1 (AI Agent Workshop - Google DevJam / Accupass)
            Event(
                id="evt_tech_devjam_ai_agent",
                title="Google DevJam 2026: Agentic AI 實戰與 GenAI 開發者小聚",
                category=EventCategory.TECH,
                description="專注於 Gemini 2.5 / 3.7 Flash、Vertex AI 與 Autonomous Agents 架構分享。提供現場實戰 Code Lab、點心與技術交流。",
                venue_name="C-LAB 臺灣當代文化實驗場 共享講堂",
                venue_id="venue_clab",
                location=Location(
                    latitude=25.0396,
                    longitude=121.5388,
                    address="台北市大安區建國南路一段177號",
                    district="大安區",
                    mrt_station="忠孝新生站 (BL14) / 忠孝復興站 (BL15)",
                    mrt_distance_meters=550,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-17T14:00:00Z",
                end_time="2026-08-17T17:30:00Z",
                tags=["AI", "技術講座", "Agent", "黑客松", "免費參加", "DevJam", "社群小聚"],
                price_type="free",
                price_amount=0,
                registration_status=RegistrationStatus.OPEN,
                source_platform="Accupass",
                capacity=120,
                estimated_duration_hours=3.5,
                rating=4.9,
                review_count=85,
                image_url="https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=60",
                source_url="https://www.accupass.com/event/devjam2026_ai_agent",
                last_updated=now_iso,
            ),
            # 5. Tech / Community Event 2 (Product & UX Meetup - Luma)
            Event(
                id="evt_tech_luma_product_ux",
                title="台北產品經理與 AI UX 設計沙龍小聚 (Product x AI)",
                category=EventCategory.WORKSHOP,
                description="探討 AI 時代下的產品探索、自然語言介面與智慧城市人流演算法。名額有限，報名附飲品與交流交流圈。",
                venue_name="POPOP Taipei 瓶蓋工廠 M棟多功能沙龍",
                venue_id="venue_popop",
                location=Location(
                    latitude=25.0531,
                    longitude=121.6062,
                    address="台北市南港區南港路二段13號",
                    district="南港區",
                    mrt_station="南港站 (BL22 地下街直通)",
                    mrt_distance_meters=180,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-17T15:00:00Z",
                end_time="2026-08-17T18:00:00Z",
                tags=["產品經理", "UX", "設計小聚", "AI", "工作坊", "Luma", "冷氣舒適"],
                price_type="paid",
                price_amount=250,
                registration_status=RegistrationStatus.OPEN,
                source_platform="Luma",
                capacity=60,
                estimated_duration_hours=3.0,
                rating=4.8,
                review_count=65,
                image_url="https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&auto=format&fit=crop&q=60",
                source_url="https://lu.ma/taipei-pm-ai-ux-2026",
                last_updated=now_iso,
            ),
            # 6. Art & Digital Media (C-LAB Media Lab)
            Event(
                id="evt_clab_future_media",
                title="【舒適私房展】C-LAB 未來媒體藝術實驗展：虛擬感知之境",
                category=EventCategory.ART,
                description="位於前空軍總部的當代前衛數位科技藝術展。全場超大空調展廳、動態音像裝置，人潮極為舒適安靜，無需排隊即可沉浸於聲光互動之中。",
                venue_name="C-LAB 臺灣當代文化實驗場 通信分隊展演空間",
                venue_id="venue_clab",
                location=Location(
                    latitude=25.0396,
                    longitude=121.5388,
                    address="台北市大安區建國南路一段177號",
                    district="大安區",
                    mrt_station="忠孝新生站 / 忠孝復興站",
                    mrt_distance_meters=550,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-17T10:00:00Z",
                end_time="2026-08-30T18:00:00Z",
                tags=["科技藝術", "新媒體", "數位互動", "免費看展", "安靜避暑", "文青必去"],
                price_type="free",
                price_amount=0,
                registration_status=RegistrationStatus.FREE_ENTRY,
                source_platform="文化部",
                capacity=300,
                estimated_duration_hours=1.5,
                rating=4.7,
                review_count=140,
                image_url="https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=60",
                source_url="https://clab.org.tw/events/future-media-2026",
                last_updated=now_iso,
            ),
            # 7. Art Museum (TFAM)
            Event(
                id="evt_tfam_contemporary_dual",
                title="臺北市立美術館：現代幾何結構與空間對話雙年展",
                category=EventCategory.ART,
                description="挑高大展廳與恆溫恆濕涼爽空間，門票僅30元，地下展區設有戶外採光中庭與精品咖啡座，適合悠閒避暑漫步。",
                venue_name="臺北市立美術館 (TFAM)",
                venue_id="venue_tfam",
                location=Location(
                    latitude=25.0722,
                    longitude=121.5248,
                    address="台北市中山區中山北路三段181號",
                    district="中山區",
                    mrt_station="圓山站 (R14)",
                    mrt_distance_meters=600,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-10T09:30:00Z",
                end_time="2026-09-01T17:30:00Z",
                tags=["當代藝術", "美術館", "冷氣", "文藝", "平價門票", "約會"],
                price_type="paid",
                price_amount=30,
                registration_status=RegistrationStatus.OPEN,
                source_platform="台北市立美術館官方",
                capacity=1200,
                estimated_duration_hours=2.5,
                rating=4.7,
                review_count=850,
                image_url="https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&auto=format&fit=crop&q=60",
                source_url="https://www.tfam.museum",
                last_updated=now_iso,
            ),
            # 8. Literature & Tea House (Kishuan)
            Event(
                id="evt_kishuan_literature_tea",
                title="【古蹟茶香】紀州庵日式古蹟文學午後茶席與選書展",
                category=EventCategory.CAFE,
                description="百年日式木造古蹟，庭園古木參天提供天然遮蔽，榻榻米茶席散發檜木香氣，享受寧靜午後時光與文學讀書會。",
                venue_name="紀州庵文學森林 古蹟大廣間",
                venue_id="venue_kishuan",
                location=Location(
                    latitude=25.0217,
                    longitude=121.5222,
                    address="台北市中正區同安街107號",
                    district="中正區",
                    mrt_station="古亭站 (G09 / O05)",
                    mrt_distance_meters=650,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-17T13:00:00Z",
                end_time="2026-08-25T18:00:00Z",
                tags=["古蹟", "日式建築", "茶席", "文學", "安靜避暑", "下午茶"],
                price_type="free",
                price_amount=0,
                registration_status=RegistrationStatus.FREE_ENTRY,
                source_platform="台北旅遊網",
                capacity=80,
                estimated_duration_hours=2.0,
                rating=4.6,
                review_count=160,
                image_url="https://images.unsplash.com/photo-1545048702-79362596cdc9?w=800&auto=format&fit=crop&q=60",
                source_url="https://kishuan.org.tw",
                last_updated=now_iso,
            ),
            # 9. Cafe Crawl & Vinyl (Chifeng Street)
            Event(
                id="evt_chifeng_cafe_crawl",
                title="赤峰街老屋獨立咖啡與黑膠唱片散策",
                category=EventCategory.CAFE,
                description="中山地下街R7出口直達，避開地面曝曬。漫步在鐵工廠與復古老宅交織的巷弄中，品嚐手沖單品與肉桂捲。",
                venue_name="赤峰街老屋文創聚落",
                venue_id="venue_chifeng",
                location=Location(
                    latitude=25.0545,
                    longitude=121.5204,
                    address="台北市大同區赤峰街49巷",
                    district="大同區",
                    mrt_station="中山站 (地下街直通)",
                    mrt_distance_meters=120,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-17T11:00:00Z",
                end_time="2026-08-30T21:00:00Z",
                tags=["咖啡", "老屋", "甜點", "黑膠", "地下街散策", "美食"],
                price_type="free",
                price_amount=0,
                registration_status=RegistrationStatus.FREE_ENTRY,
                source_platform="台北旅遊網",
                capacity=150,
                estimated_duration_hours=2.0,
                rating=4.6,
                review_count=420,
                image_url="https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=60",
                source_url="https://travel.taipei/events/chifeng",
                last_updated=now_iso,
            ),
            # 10. Outdoor Fireworks (Dadaocheng - Summer Fest)
            Event(
                id="evt_dadaocheng_fireworks_2026",
                title="2026 大稻埕夏日節：水岸夕陽煙火音樂大賞",
                category=EventCategory.FOOD,
                description="台北夏季指標盛事！淡水河畔異國美食市集、live band 舞台與千發煙火秀。週邊交通管制且人潮極度擁擠（高溫無冷氣）。",
                venue_name="大稻埕碼頭貨櫃市集",
                venue_id="venue_dadaocheng",
                location=Location(
                    latitude=25.0569,
                    longitude=121.5076,
                    address="台北市大同區民生西路底五號水門",
                    district="大同區",
                    mrt_station="北門站 / 雙連站",
                    mrt_distance_meters=1100,
                ),
                is_indoor=False,
                ac_available=False,
                start_time="2026-08-17T16:00:00Z",
                end_time="2026-08-17T22:30:00Z",
                tags=["煙火", "音樂節", "夕陽", "美食", "戶外人潮極高", "大稻埕夏日節"],
                price_type="free",
                price_amount=0,
                registration_status=RegistrationStatus.FREE_ENTRY,
                source_platform="台北市觀傳局官方",
                capacity=2000,
                estimated_duration_hours=3.5,
                rating=4.5,
                review_count=1200,
                image_url="https://images.unsplash.com/photo-1533230408708-8f9f91d1235a?w=800&auto=format&fit=crop&q=60",
                source_url="https://taipeisummer.travel.taipei",
                last_updated=now_iso,
            ),
            # 11. Music Experience (TMC)
            Event(
                id="evt_tmc_pop_music_history",
                title="唱我們的歌：流行音樂故事沉浸常設展",
                category=EventCategory.MUSIC,
                description="全台最大流行音樂主題展，配備紅外線感應耳機隨走隨聽，十三個沉浸展區，環境舒適寬敞，音樂愛好者必訪。",
                venue_name="臺北流行音樂中心 文化館",
                venue_id="venue_tmc",
                location=Location(
                    latitude=25.0519,
                    longitude=121.5975,
                    address="台北市南港區市民大道八段99號",
                    district="南港區",
                    mrt_station="昆陽站 / 南港站",
                    mrt_distance_meters=400,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-01T10:00:00Z",
                end_time="2026-12-31T18:00:00Z",
                tags=["音樂", "展覽", "耳機互動", "室內吹冷氣", "舒適人潮", "親子情侶"],
                price_type="paid",
                price_amount=350,
                registration_status=RegistrationStatus.OPEN,
                source_platform="KKTIX",
                capacity=600,
                estimated_duration_hours=2.5,
                rating=4.8,
                review_count=350,
                image_url="https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=60",
                source_url="https://tmc.kktix.cc/events/singourmusic",
                last_updated=now_iso,
            ),
            # 12. Tech Family Interactive (NTSEC)
            Event(
                id="evt_ntsec_ai_future_lab",
                title="AI 未來探索實驗室：沉浸式科技與機器人互動特展",
                category=EventCategory.TECH,
                description="適合親子與科技愛好者的全室內大型互動展，強效空調冷氣，探索生成式AI、人形機器人與未來城市交互。",
                venue_name="國立臺灣科學教育館 7樓特展區",
                venue_id="venue_ntsec",
                location=Location(
                    latitude=25.0957,
                    longitude=121.5165,
                    address="台北市士林區士商路189號",
                    district="士林區",
                    mrt_station="士林站 (R16 接駁公車 / 步行)",
                    mrt_distance_meters=900,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-01T09:00:00Z",
                end_time="2026-09-15T18:00:00Z",
                tags=["科技", "AI", "親子", "室內冷氣", "教育互動", "工作坊"],
                price_type="paid",
                price_amount=280,
                registration_status=RegistrationStatus.OPEN,
                source_platform="KKTIX",
                capacity=700,
                estimated_duration_hours=3.0,
                rating=4.6,
                review_count=520,
                image_url="https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=60",
                source_url="https://www.ntsec.gov.tw/events/ai-lab",
                last_updated=now_iso,
            ),
            # 13. Historical Walk (Bopiliao)
            Event(
                id="evt_bopiliao_historic_walk",
                title="艋舺時光印記：剝皮寮老街歷史故事常設展",
                category=EventCategory.ART,
                description="清代與日治時期紅磚騎樓長廊，提供絕佳天然遮陽廊道，免費探索萬華老城故事與傳統手藝。",
                venue_name="剝皮寮歷史街區 演藝廳與紅磚街區",
                venue_id="venue_bopiliao",
                location=Location(
                    latitude=25.0371,
                    longitude=121.5020,
                    address="台北市萬華區廣州街101號",
                    district="萬華區",
                    mrt_station="龍山寺站 (BL10)",
                    mrt_distance_meters=300,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-10T09:00:00Z",
                end_time="2026-08-31T17:30:00Z",
                tags=["歷史", "古蹟", "紅磚長廊", "遮陽", "免費看展", "萬華美食"],
                price_type="free",
                price_amount=0,
                registration_status=RegistrationStatus.FREE_ENTRY,
                source_platform="台北旅遊網",
                capacity=200,
                estimated_duration_hours=1.5,
                rating=4.5,
                review_count=310,
                image_url="https://images.unsplash.com/photo-1508807526345-15e9b5f4eaff?w=800&auto=format&fit=crop&q=60",
                source_url="https://www.bopiliao.taipei",
                last_updated=now_iso,
            ),
            # 14. Architecture Tour (TPAC)
            Event(
                id="evt_tpac_architect_tour",
                title="【球劇場揭秘】臺北表演藝術中心 建築與公共藝術沉浸導覽",
                category=EventCategory.ART,
                description="由普立茲克得主庫哈斯（Rem Koolhaas）設計，全室內參觀迴路穿梭於劇院後台與巨型球體空間，直通劍潭捷運站。",
                venue_name="臺北表演藝術中心 (TPAC)",
                venue_id="venue_tpac",
                location=Location(
                    latitude=25.0877,
                    longitude=121.5262,
                    address="台北市士林區劍潭路1號",
                    district="士林區",
                    mrt_station="劍潭站",
                    mrt_distance_meters=80,
                ),
                is_indoor=True,
                ac_available=True,
                start_time="2026-08-17T10:00:00Z",
                end_time="2026-08-28T17:00:00Z",
                tags=["建築", "劇場", "設計", "室內導覽", "捷運直達", "冷氣"],
                price_type="paid",
                price_amount=150,
                registration_status=RegistrationStatus.OPEN,
                source_platform="OPENTIX",
                capacity=250,
                estimated_duration_hours=1.5,
                rating=4.5,
                review_count=210,
                image_url="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=60",
                source_url="https://tpac.org.tw/events/architect-tour",
                last_updated=now_iso,
            ),
        ]
